package rl78g12

import ghidra.app.decompiler.DecompInterface
import ghidra.app.plugin.ProgramPlugin
import ghidra.framework.plugintool.PluginInfo
import ghidra.framework.plugintool.PluginTool
import ghidra.framework.plugintool.util.PluginStatus
import ghidra.program.model.listing.Program
import ghidra.program.model.symbol.SourceType
import ghidra.program.model.pcode.HighFunctionDBUtil
import ghidra.util.Msg
import ghidra.util.exception.InvalidInputException
import ghidra.util.task.TaskMonitor

@PluginInfo(
  status = PluginStatus.STABLE,
  packageName = "RL78G12",
  category = "Analysis",
  shortDescription = "Rename RL78 interrupt handlers",
  description = "Adds labels for RL78 interrupt targets from vector table and renames autogenerated locals"
)
class RL78G12Plugin(tool: PluginTool) extends ProgramPlugin(tool) {

  private var done = false

  private def createOrRenameLabel(
    program: Program,
    addrValue: Long,
    name: String
  ): Unit =
    val st = program.getSymbolTable
    val af = program.getAddressFactory.getDefaultAddressSpace
    val a = af.getAddress(addrValue)

    val primary = st.getPrimarySymbol(a)
    if primary == null then
      st.createLabel(a, name, SourceType.ANALYSIS)
    else
      try primary.setName(name, SourceType.ANALYSIS)
      catch
        case _: Exception => ()

  private val vectors = Seq(
    0x0000 -> "RESET",
    0x0004 -> "INTWDTI",
    0x0006 -> "INTLVI",
    0x0008 -> "INTP0",
    0x000A -> "INTP1",
    0x000C -> "INTP2",
    0x000E -> "INTP3",
    0x0010 -> "INTDMA0",
    0x0012 -> "INTDMA1",
    0x0014 -> "INTST0_INTCSI00_INTIIC00",
    0x0016 -> "INTSR0_INTCSI01_INTIIC01",
    0x0018 -> "INTSRE0",
    0x001A -> "INTTM01H",
    0x001C -> "INTTM03H",
    0x001E -> "INTIICA0",
    0x0020 -> "INTTM00",
    0x0022 -> "INTTM01",
    0x0024 -> "INTTM02",
    0x0026 -> "INTTM03",
    0x0028 -> "INTAD",
    0x002A -> "INTIT",
    0x002C -> "INTKR",
    0x002E -> "INTMD",
    0x0030 -> "INTFL",
    0x007E -> "BRK"
  )

  private val tempVarRe =
    """^(?:local(?:_res)?_[0-9A-Fa-f]+|(?:param|temp)_[0-9A-Fa-f]+|(?:b|s|u|i|l|ll|f|d|c|a|p|pc|pu)(?:Var|Stack)?[A-Za-z0-9_]*\d+)$""".r

  override protected def programActivated(program: Program): Unit =
    if !done then
      done = true
      setupMemoryMap(program)
      annotateKnownRegions(program)
      renameDecompilerTemps(program)
      renameInterrupts(program)

  private def annotateKnownRegions(program: Program): Unit =
    val tx = program.startTransaction("Annotate RL78/G12 regions")
    try
      // Region-level labels
      createOrRenameLabel(program, 0x0000, "VECTOR_TABLE")
      createOrRenameLabel(program, 0x0080, "CALLT_TABLE")
      createOrRenameLabel(program, 0x00C0, "OPTION_BYTES")
      createOrRenameLabel(program, 0x00C4, "SECURITY_ID")

      // Per-entry vector labels
      annotateVectorEntries(program)

      Msg.showInfo(this, null, "RL78G12", "Known regions annotated.")
    catch
      case e: Exception =>
        Msg.showError(this, null, "RL78G12", s"Failed to annotate known regions: ${e.getMessage}", e)
    finally
      program.endTransaction(tx, true)

  import ghidra.app.cmd.function.CreateFunctionCmd
  private def ensureFunction(program: Program, entry: ghidra.program.model.address.Address, name: String): Unit =
    val fm = program.getFunctionManager
    var fn = fm.getFunctionAt(entry)

    if fn == null then
      val cmd = new CreateFunctionCmd(name, entry, null, SourceType.ANALYSIS)
      cmd.applyTo(program)

    fn = fm.getFunctionAt(entry)
    if fn != null then
      try
        fn.setName(name, SourceType.ANALYSIS)
      catch
        case _: Exception => ()

  private def setupMemoryMap(program: Program): Unit =
    val tx = program.startTransaction("Setup RL78/G12 memory map")
    try
      val mem = program.getMemory
      val af  = program.getAddressFactory.getDefaultAddressSpace

      def addr(x: Long) = af.getAddress(x)

      def createUninitializedBlock(name: String, start: Long, end: Long, read: Boolean, write: Boolean, execute: Boolean, volatile: Boolean = false): Unit =
        val startAddr = addr(start)
        if mem.getBlock(startAddr) == null then
          val size = end - start + 1
          val block = mem.createUninitializedBlock(name, startAddr, size, false)
          block.setRead(read)
          block.setWrite(write)
          block.setExecute(execute)
          block.setVolatile(volatile)
          Msg.info(this, s"Created block $name @ ${start.toHexString}-${end.toHexString}")
        else
          Msg.info(this, s"Block already exists at ${start.toHexString}: $name")

      def createOverlayOrSubBlock(name: String, start: Long, end: Long, read: Boolean, write: Boolean, execute: Boolean): Unit =
        val startAddr = addr(start)
        if mem.getBlock(startAddr) == null then
          val size = end - start + 1
          val block = mem.createUninitializedBlock(name, startAddr, size, false)
          block.setRead(read)
          block.setWrite(write)
          block.setExecute(execute)
          Msg.info(this, s"Created block $name @ ${start.toHexString}-${end.toHexString}")

      // Core blocks
      createUninitializedBlock("CODE",       0x00000, 0x007FF, read = true,  write = false, execute = true)
      createUninitializedBlock("SFR2",       0xF0000, 0xF07FF, read = true,  write = true,  execute = false, volatile = true)
      createUninitializedBlock("DATA_FLASH", 0xF1000, 0xF17FF, read = true,  write = true,  execute = false)
      createUninitializedBlock("RAM",        0xFFE00, 0xFFEFF, read = true,  write = true,  execute = false)
      createUninitializedBlock("SFR",        0xFFF00, 0xFFFFF, read = true,  write = true,  execute = false, volatile = true)

      // Optional named ROM subregions if not already separately defined
      createOverlayOrSubBlock("VECTORS",      0x00000, 0x0007F, read = true, write = false, execute = false)
      createOverlayOrSubBlock("CALLT",        0x00080, 0x000BF, read = true, write = false, execute = false)
      createOverlayOrSubBlock("OPTION_BYTES", 0x000C0, 0x000C3, read = true, write = false, execute = false)
      createOverlayOrSubBlock("SECURITY_ID",  0x000C4, 0x000CD, read = true, write = false, execute = false)

      Msg.showInfo(this, null, "RL78G12", "Memory map setup complete.")
    catch
      case e: Exception =>
        Msg.showError(this, null, "RL78G12", s"Failed to setup memory map: ${e.getMessage}", e)
    finally
      program.endTransaction(tx, true)
    
  private def renameInterrupts(program: Program): Unit =
    val tx = program.startTransaction("Label RL78 interrupt targets")
    try
      val mem = program.getMemory
      val st  = program.getSymbolTable
      val af  = program.getAddressFactory.getDefaultAddressSpace

      for ((vec, name) <- vectors) do
        val vecAddr = af.getAddress(vec.toLong)

        if mem.contains(vecAddr) && mem.contains(vecAddr.add(1)) then
          val lo = mem.getByte(vecAddr) & 0xff
          val hi = mem.getByte(vecAddr.add(1)) & 0xff
          val target = (hi << 8) | lo

          if target != 0x0000 && target != 0xffff then
            val targetAddr = af.getAddress(target.toLong)
            ensureFunction(program, targetAddr, name)
            val syms = st.getSymbols(targetAddr)

            if syms.isEmpty then
              st.createLabel(targetAddr, name, SourceType.ANALYSIS)
            else
              val primary = st.getPrimarySymbol(targetAddr)
              if primary != null then
                try
                  primary.setName(name, SourceType.ANALYSIS)
                catch
                  case _: Exception =>
                    st.createLabel(targetAddr, f"${name}_${target}%04X", SourceType.ANALYSIS)

      Msg.showInfo(this, null, "RL78G12", "Interrupt labels added.")
    catch
      case e: Exception =>
        Msg.showError(this, null, "RL78G12", s"Failed to label interrupts: ${e.getMessage}", e)
    finally
      program.endTransaction(tx, true)

  private def renameDecompilerTemps(program: Program): Unit =
    val tx = program.startTransaction("Rename decompiler temps")
    val ifc = new DecompInterface()

    try
      if !ifc.openProgram(program) then
        Msg.showError(this, null, "RL78G12", "Failed to open program in decompiler interface.")
        return

      val fm = program.getFunctionManager
      val it = fm.getFunctions(true)

      var funcsVisited = 0
      var localsRenamed = 0

      while it.hasNext do
        val func = it.next()
        funcsVisited += 1

        val res = ifc.decompileFunction(func, 30, TaskMonitor.DUMMY)

        if res == null then
          Msg.warn(this, s"${func.getName}: decompile returned null")
        else if !res.decompileCompleted() then
          Msg.warn(this, s"${func.getName}: decompile failed: ${res.getErrorMessage}")
        else
          val hf = res.getHighFunction
          if hf == null then
            Msg.warn(this, s"${func.getName}: high function is null")
          else
            HighFunctionDBUtil.commitLocalNamesToDatabase(hf, SourceType.ANALYSIS)

            val locals = func.getLocalVariables
            var localIdx = 1

            for local <- locals do
              val oldName = local.getName
              if isTempName(oldName) then
                val newName = nextUniqueLocalName(func, localIdx)
                localIdx += 1

                try
                  local.setName(newName, SourceType.ANALYSIS)
                  localsRenamed += 1
                catch
                  case _: InvalidInputException =>
                    val fallback = nextUniqueNameFromBase(func, s"${newName}_")
                    try
                      local.setName(fallback, SourceType.ANALYSIS)
                      localsRenamed += 1
                    catch
                      case e: Exception =>
                        Msg.warn(this, s"${func.getName}: failed to rename local $oldName: ${e.getMessage}")

        ifc.flushCache()

      Msg.showInfo(
        this,
        null,
        "RL78G12",
        s"Decompiler-temp pass complete. Functions visited: $funcsVisited, locals renamed: $localsRenamed"
      )
    catch
      case e: Exception =>
        Msg.showError(this, null, "RL78G12", s"Failed to rename decompiler temps: ${e.getMessage}", e)
    finally
      ifc.dispose()
      program.endTransaction(tx, true)

  private def isTempName(name: String): Boolean =
    tempVarRe.matches(name)

  private def nextUniqueLocalName(func: ghidra.program.model.listing.Function, startIdx: Int): String =
    var idx = startIdx
    var candidate = s"local_$idx"
    while hasVariableNamed(func, candidate) do
      idx += 1
      candidate = s"local_$idx"
    candidate

  private def nextUniqueNameFromBase(func: ghidra.program.model.listing.Function, base: String): String =
    var idx = 1
    var candidate = s"${base}$idx"
    while hasVariableNamed(func, candidate) do
      idx += 1
      candidate = s"${base}$idx"
    candidate

  private def hasVariableNamed(func: ghidra.program.model.listing.Function, name: String): Boolean =
    val allVars = func.getAllVariables
    allVars.exists(_.getName == name)
}
