package rl78g12

import ghidra.app.cmd.function.CreateFunctionCmd
import ghidra.app.decompiler.DecompInterface
import ghidra.app.plugin.ProgramPlugin
import ghidra.framework.plugintool.PluginInfo
import ghidra.framework.plugintool.PluginTool
import ghidra.framework.plugintool.util.PluginStatus
import ghidra.program.model.address.Address
import ghidra.program.model.data.ByteDataType
import ghidra.program.model.data.WordDataType
import ghidra.program.model.listing.CodeUnit
import ghidra.program.model.listing.Function
import ghidra.program.model.listing.Program
import ghidra.program.model.mem.MemoryBlock
import ghidra.program.model.pcode.HighFunctionDBUtil
import ghidra.program.model.symbol.SourceType
import ghidra.util.Msg
import ghidra.util.exception.InvalidInputException
import ghidra.util.task.TaskMonitor

@PluginInfo(
  status = PluginStatus.STABLE,
  packageName = "RL78G12",
  category = "Analysis",
  shortDescription = "Annotate RL78/G12 vectors, memory map, and locals",
  description =
    "Sets up RL78/G12 memory map, annotates vector/CALLT/option/security regions, names interrupt handlers, and renames autogenerated locals"
)
class RL78G12Plugin(tool: PluginTool) extends ProgramPlugin(tool) {

  private var done = false

  private val registers = Seq(
    0xFFF00L -> "P0",
    0xFFF01L -> "P1",
    0xFFF02L -> "P2",
    0xFFF03L -> "P3",
    0xFFF04L -> "P4",
    0xFFF05L -> "P5",
    0xFFF06L -> "P6",
    0xFFF0CL -> "P12",
    0xFFF0DL -> "P13",
    0xFFF0EL -> "P14",
    0xFFF10L -> "SDR00",
    0xFFF10L -> "SIO00",
    0xFFF10L -> "TXD0",
    0xFFF12L -> "SDR01",
    0xFFF12L -> "RXD0",
    0xFFF18L -> "TDR00",
    0xFFF1AL -> "TDR01",
    0xFFF1AL -> "TDR01L",
    0xFFF1BL -> "TDR01H",
    0xFFF1EL -> "ADCR",
    0xFFF1FL -> "ADCRH",
    0xFFF20L -> "PM0",
    0xFFF21L -> "PM1",
    0xFFF22L -> "PM2",
    0xFFF23L -> "PM3",
    0xFFF24L -> "PM4",
    0xFFF25L -> "PM5",
    0xFFF26L -> "PM6",
    0xFFF2CL -> "PM12",
    0xFFF2EL -> "PM14",
    0xFFF30L -> "ADM0",
    0xFFF31L -> "ADS",
    0xFFF32L -> "ADM1",
    0xFFF38L -> "EGP0",
    0xFFF39L -> "EGN0",
    0xFFF44L -> "SDR02",
    0xFFF44L -> "TXD1",
    0xFFF46L -> "SDR03",
    0xFFF46L -> "RXD1",
    0xFFF46L -> "SIO11",
    0xFFF48L -> "SDR10",
    0xFFF48L -> "SIO20",
    0xFFF48L -> "TXD2",
    0xFFF4AL -> "SDR11",
    0xFFF4AL -> "RXD2",
    0xFFF50L -> "IICA0",
    0xFFF51L -> "IICS0",
    0xFFF52L -> "IICF0",
    0xFFF64L -> "TDR02",
    0xFFF66L -> "TDR03",
    0xFFF66L -> "TDR03L",
    0xFFF67L -> "TDR03H",
    0xFFF68L -> "TDR04",
    0xFFF6AL -> "TDR05",
    0xFFF6CL -> "TDR06",
    0xFFF6EL -> "TDR07",
    0xFFF90L -> "ITMC",
    0xFFFA0L -> "CMC",
    0xFFFA1L -> "CSC",
    0xFFFA2L -> "OSTC",
    0xFFFA3L -> "OSTS",
    0xFFFA4L -> "CKC",
    0xFFFA5L -> "CKS0",
    0xFFFA6L -> "CKS1",
    0xFFFA8L -> "RESF",
    0xFFFA9L -> "LVIM",
    0xFFFAAL -> "LVIS",
    0xFFFABL -> "WDTE",
    0xFFFACL -> "CRCIN",
    0xFFFB0L -> "DSA0",
    0xFFFB1L -> "DSA1",
    0xFFFB2L -> "DRA0",
    0xFFFB2L -> "DRA0L",
    0xFFFB3L -> "DRA0H",
    0xFFFB4L -> "DRA1",
    0xFFFB4L -> "DRA1L",
    0xFFFB5L -> "DRA1H",
    0xFFFB6L -> "DBC0",
    0xFFFB6L -> "DBC0L",
    0xFFFB7L -> "DBC0H",
    0xFFFB8L -> "DBC1",
    0xFFFB8L -> "DBC1L",
    0xFFFB9L -> "DBC1H",
    0xFFFBAL -> "DMC0",
    0xFFFBBL -> "DMC1",
    0xFFFBCL -> "DRC0",
    0xFFFBDL -> "DRC1",
    0xFFFD0L -> "IF2",
    0xFFFD0L -> "IF2L",
    0xFFFD1L -> "IF2H",
    0xFFFD4L -> "MK2",
    0xFFFD4L -> "MK2L",
    0xFFFD5L -> "MK2H",
    0xFFFD8L -> "PR02",
    0xFFFD8L -> "PR02L",
    0xFFFD9L -> "PR02H",
    0xFFFDCL -> "PR12",
    0xFFFDCL -> "PR12L",
    0xFFFDDL -> "PR12H",
    0xFFFE0L -> "IF0",
    0xFFFE0L -> "IF0L",
    0xFFFE1L -> "IF0H",
    0xFFFE2L -> "IF1",
    0xFFFE2L -> "IF1L",
    0xFFFE3L -> "IF1H",
    0xFFFE4L -> "MK0",
    0xFFFE4L -> "MK0L",
    0xFFFE5L -> "MK0H",
    0xFFFE6L -> "MK1",
    0xFFFE6L -> "MK1L",
    0xFFFE7L -> "MK1H",
    0xFFFE8L -> "PR00",
    0xFFFE8L -> "PR00L",
    0xFFFE9L -> "PR00H",
    0xFFFEAL -> "PR01",
    0xFFFEAL -> "PR01L",
    0xFFFEBL -> "PR01H",
    0xFFFECL -> "PR10",
    0xFFFECL -> "PR10L",
    0xFFFEDL -> "PR10H",
    0xFFFEEL -> "PR11",
    0xFFFEEL -> "PR11L",
    0xFFFEFL -> "PR11H",
    0xFFFF0L -> "MDAL",
    0xFFFF0L -> "MULA",
    0xFFFF2L -> "MDAH",
    0xFFFF2L -> "MULB",
    0xFFFF4L -> "MDBH",
    0xFFFF4L -> "MULOH",
    0xFFFF6L -> "MDBL",
    0xFFFF6L -> "MULOL",
    0xFFFFEL -> "PMC",
    0xF0010L -> "ADM2",
    0xF0011L -> "ADUL",
    0xF0012L -> "ADLL",
    0xF0013L -> "ADTES",
    0xF0030L -> "PU0",
    0xF0031L -> "PU1",
    0xF0033L -> "PU3",
    0xF0034L -> "PU4",
    0xF0035L -> "PU5",
    0xF003CL -> "PU12",
    0xF003EL -> "PU14",
    0xF0040L -> "PIM0",
    0xF0041L -> "PIM1",
    0xF0050L -> "POM0",
    0xF0051L -> "POM1",
    0xF0055L -> "POM5",
    0xF0060L -> "PMC0",
    0xF006CL -> "PMC12",
    0xF006EL -> "PMC14",
    0xF0070L -> "NFEN0",
    0xF0071L -> "NFEN1",
    0xF0073L -> "ISC",
    0xF0074L -> "TIS0",
    0xF0076L -> "ADPC",
    0xF0077L -> "PIOR",
    0xF0078L -> "IAWCTL",
    0xF0090L -> "DFLCTL",
    0xF00A0L -> "HIOTRM",
    0xF00A8L -> "HOCODIV",
    0xF00ACL -> "TEMPCAL0",
    0xF00ADL -> "TEMPCAL1",
    0xF00AEL -> "TEMPCAL2",
    0xF00AFL -> "TEMPCAL3",
    0xF00E0L -> "MDCL",
    0xF00E2L -> "MDCH",
    0xF00E8L -> "MDUC",
    0xF00F0L -> "PER0",
    0xF00F3L -> "OSMC",
    0xF00F4L -> "RMC",
    0xF00F5L -> "RPECTL",
    0xF00FEL -> "BCDADJ",
    0xF0100L -> "SSR00",
    0xF0102L -> "SSR01",
    0xF0104L -> "SSR02",
    0xF0106L -> "SSR03",
    0xF0108L -> "SIR00",
    0xF010AL -> "SIR01",
    0xF010CL -> "SIR02",
    0xF010EL -> "SIR03",
    0xF0110L -> "SMR00",
    0xF0112L -> "SMR01",
    0xF0114L -> "SMR02",
    0xF0116L -> "SMR03",
    0xF0118L -> "SCR00",
    0xF011AL -> "SCR01",
    0xF011CL -> "SCR02",
    0xF011EL -> "SCR03",
    0xF0120L -> "SE0",
    0xF0122L -> "SS0",
    0xF0124L -> "ST0",
    0xF0126L -> "SPS0",
    0xF0128L -> "SO0",
    0xF012AL -> "SOE0",
    0xF0134L -> "SOL0",
    0xF0138L -> "SSC0",
    0xF0140L -> "SSR10",
    0xF0142L -> "SSR11",
    0xF0148L -> "SIR10",
    0xF014AL -> "SIR11",
    0xF0150L -> "SMR10",
    0xF0152L -> "SMR11",
    0xF0158L -> "SCR10",
    0xF015AL -> "SCR11",
    0xF0160L -> "SE1",
    0xF0162L -> "SS1",
    0xF0164L -> "ST1",
    0xF0166L -> "SPS1",
    0xF0168L -> "SO1",
    0xF016AL -> "SOE1",
    0xF0174L -> "SOL1",
    0xF0180L -> "TCR00",
    0xF0182L -> "TCR01",
    0xF0184L -> "TCR02",
    0xF0186L -> "TCR03",
    0xF0188L -> "TCR04",
    0xF018AL -> "TCR05",
    0xF018CL -> "TCR06",
    0xF018EL -> "TCR07",
    0xF0190L -> "TMR00",
    0xF0192L -> "TMR01",
    0xF0194L -> "TMR02",
    0xF0196L -> "TMR03",
    0xF0198L -> "TMR04",
    0xF019AL -> "TMR05",
    0xF019CL -> "TMR06",
    0xF019EL -> "TMR07",
    0xF01A0L -> "TSR00",
    0xF01A2L -> "TSR01",
    0xF01A4L -> "TSR02",
    0xF01A6L -> "TSR03",
    0xF01A8L -> "TSR04",
    0xF01AAL -> "TSR05",
    0xF01ACL -> "TSR06",
    0xF01AEL -> "TSR07",
    0xF01B0L -> "TE0",
    0xF01B2L -> "TS0",
    0xF01B4L -> "TT0",
    0xF01B6L -> "TPS0",
    0xF01B8L -> "TO0",
    0xF01BAL -> "TOE0",
    0xF01BCL -> "TOL0",
    0xF01BEL -> "TOM0",
    0xF0230L -> "IICCTL00",
    0xF0231L -> "IICCTL01",
    0xF0232L -> "IICWL0",
    0xF0233L -> "IICWH0",
    0xF0234L -> "SVA0",
    0xF02F0L -> "CRC0CTL",
    0xF02F2L -> "PGCRCL",
    0xF02FAL -> "CRCD"
  )

  private val vectors = Seq(
    0x0000 -> "RESET",
    0x0004 -> "INTWDTI",
    0x0006 -> "INTLVI",
    0x0008 -> "INTP0",
    0x000A -> "INTP1",
    0x000C -> "INTP2",
    0x000E -> "INTP3",
    0x0010 -> "INTDMA0",
    0x0012 -> "INTDMA1",
    0x0014 -> "INTST0_INTCSI00_INTIIC00",
    0x0016 -> "INTSR0_INTCSI01_INTIIC01",
    0x0018 -> "INTSRE0",
    0x001A -> "INTTM01H",
    0x001C -> "INTTM03H",
    0x001E -> "INTIICA0",
    0x0020 -> "INTTM00",
    0x0022 -> "INTTM01",
    0x0024 -> "INTTM02",
    0x0026 -> "INTTM03",
    0x0028 -> "INTAD",
    0x002A -> "INTIT",
    0x002C -> "INTKR",
    0x002E -> "INTMD",
    0x0030 -> "INTFL",
    0x007E -> "BRK"
  )

  private def hasSymbolNamed(program: Program, addrValue: Long, name: String): Boolean =
    val st = program.getSymbolTable
    val syms = st.getSymbols(addr(program, addrValue))
    syms.exists(_.getName == name)

  private def createLabelAlias(program: Program, addrValue: Long, name: String, makePrimary: Boolean): Unit =
    val st = program.getSymbolTable
    val a = addr(program, addrValue)

    if !hasSymbolNamed(program, addrValue, name) then
      val sym = st.createLabel(a, name, SourceType.ANALYSIS)
      if makePrimary && sym != null then
        try sym.setPrimary()
        catch case _: Exception => ()

  private def looksLikeWordRegister(name: String): Boolean =
    !(name.endsWith("H") || name.endsWith("L")) &&
      (
        name.matches(""".*\d\d$""") ||
        Set(
          "ADCR", "ITMC", "CRC0CTL", "PGCRCL", "CRCD",
          "IICA0", "SSR00", "SSR01", "SSR02", "SSR03", "SSR10", "SSR11",
          "SIR00", "SIR01", "SIR02", "SIR03", "SIR10", "SIR11",
          "SMR00", "SMR01", "SMR02", "SMR03", "SMR10", "SMR11",
          "SCR00", "SCR01", "SCR02", "SCR03", "SCR10", "SCR11",
          "SE0", "SS0", "ST0", "SPS0", "SO0", "SOE0", "SOL0", "SSC0",
          "SE1", "SS1", "ST1", "SPS1", "SO1", "SOE1", "SOL1",
          "TCR00", "TCR01", "TCR02", "TCR03", "TCR04", "TCR05", "TCR06", "TCR07",
          "TMR00", "TMR01", "TMR02", "TMR03", "TMR04", "TMR05", "TMR06", "TMR07",
          "TSR00", "TSR01", "TSR02", "TSR03", "TSR04", "TSR05", "TSR06", "TSR07",
          "TE0", "TS0", "TT0", "TPS0", "TO0", "TOE0", "TOL0", "TOM0",
          "IF0", "IF1", "IF2", "MK0", "MK1", "MK2",
          "PR00", "PR01", "PR02", "PR10", "PR11", "PR12",
          "SDR00", "SDR01", "SDR02", "SDR03", "SDR10", "SDR11",
          "TDR00", "TDR01", "TDR02", "TDR03", "TDR04", "TDR05", "TDR06", "TDR07",
          "DRA0", "DRA1", "DBC0", "DBC1"
        ).contains(name)
      )

  private def ensureRegisterData(program: Program, addrValue: Long, names: Seq[String]): Unit =
    val listing = program.getListing
    val a = addr(program, addrValue)
    if listing.getInstructionAt(a) != null then return

    val hasHighLowAliases = names.exists(_.endsWith("L")) || names.exists(_.endsWith("H"))
    val preferWord = names.exists(looksLikeWordRegister) || hasHighLowAliases

    if listing.getDataAt(a) == null then
      try
        if preferWord then listing.createData(a, WordDataType.dataType)
        else listing.createData(a, ByteDataType.dataType)
      catch
        case _: Exception => ()

  private val tempVarRe =
    """^(?:local(?:_res)?_[0-9A-Fa-f]+|(?:param|temp)_[0-9A-Fa-f]+|(?:b|s|u|i|l|ll|f|d|c|a|p|pc|pu)(?:Var|Stack)?[A-Za-z0-9_]*\d+)$""".r

  override protected def programActivated(program: Program): Unit =
    if !done then
      try
        setupMemoryMap(program)
        annotateKnownRegions(program)
        annotateRegisters(program)
        renameInterrupts(program)
        renameDecompilerTemps(program)
        done = true
      catch
        case e: Exception =>
          done = false
          Msg.showError(this, null, "RL78G12", s"Plugin failed: ${e.getMessage}", e)

  private def addr(program: Program, x: Long): Address =
    program.getAddressFactory.getDefaultAddressSpace.getAddress(x)

  private def annotateRegisters(program: Program): Unit =
    val tx = program.startTransaction("Annotate RL78/G12 registers")
    try
      val grouped = registers.groupBy(_._1).toSeq.sortBy(_._1)

      for (regAddr, entries) <- grouped do
        val names = entries.map(_._2).distinct
        if names.nonEmpty then
          ensureRegisterData(program, regAddr, names)

          val primary = names.head
          createLabelAlias(program, regAddr, primary, makePrimary = true)

          for alias <- names.tail do
            createLabelAlias(program, regAddr, alias, makePrimary = false)

          val aliasText =
            if names.tail.nonEmpty then s"Aliases: ${names.tail.mkString(", ")}"
            else "No aliases"

          val widthText =
            if names.exists(_.endsWith("L")) || names.exists(_.endsWith("H")) || names.exists(looksLikeWordRegister) then
              "Register width: likely 16-bit or mixed 8/16-bit view"
            else
              "Register width: likely 8-bit"

          setPreComment(program, regAddr, s"SFR/SFR2 register: $primary")
          setEolComment(program, regAddr, s"$aliasText; $widthText")

      Msg.showInfo(this, null, "RL78G12", s"Annotated ${grouped.size} register addresses.")
    catch
      case e: Exception =>
        Msg.showError(this, null, "RL78G12", s"Failed to annotate registers: ${e.getMessage}", e)
    finally
      program.endTransaction(tx, true)

  private def createOrRenameLabel(program: Program, addrValue: Long, name: String): Unit =
    val st = program.getSymbolTable
    val a = addr(program, addrValue)

    val primary = st.getPrimarySymbol(a)
    if primary == null then
      st.createLabel(a, name, SourceType.ANALYSIS)
    else
      try
        primary.setName(name, SourceType.ANALYSIS)
      catch
        case _: Exception =>
          try
            st.createLabel(a, s"${name}_${addrValue.toHexString.toUpperCase}", SourceType.ANALYSIS)
          catch
            case _: Exception => ()

  private def appendComment(existing: String, extra: String): String =
    if existing == null || existing.isBlank then extra
    else if existing.contains(extra) then existing
    else existing + "\n" + extra

  private def setPreComment(program: Program, addrValue: Long, text: String): Unit =
    val listing = program.getListing
    val cu = listing.getCodeUnitAt(addr(program, addrValue))
    if cu != null then
      cu.setComment(CodeUnit.PRE_COMMENT, appendComment(cu.getComment(CodeUnit.PRE_COMMENT), text))

  private def setEolComment(program: Program, addrValue: Long, text: String): Unit =
    val listing = program.getListing
    val cu = listing.getCodeUnitAt(addr(program, addrValue))
    if cu != null then
      cu.setComment(CodeUnit.EOL_COMMENT, appendComment(cu.getComment(CodeUnit.EOL_COMMENT), text))

  private def ensureByteData(program: Program, addrValue: Long): Unit =
    val listing = program.getListing
    val a = addr(program, addrValue)
    if listing.getDataAt(a) == null && listing.getInstructionAt(a) == null then
      try
        listing.createData(a, ByteDataType.dataType)
      catch
        case _: Exception => ()

  private def ensureWordData(program: Program, addrValue: Long): Unit =
    val listing = program.getListing
    val a = addr(program, addrValue)
    if listing.getDataAt(a) == null && listing.getInstructionAt(a) == null then
      try
        listing.createData(a, WordDataType.dataType)
      catch
        case _: Exception => ()

  private def ensureRegionLabel(program: Program, addrValue: Long, name: String, comment: String): Unit =
    createOrRenameLabel(program, addrValue, name)
    setPreComment(program, addrValue, comment)

  private def ensureFunction(program: Program, entry: Address, name: String): Unit =
    val fm = program.getFunctionManager
    var fn = fm.getFunctionAt(entry)

    if fn == null then
      val cmd = new CreateFunctionCmd(name, entry, null, SourceType.ANALYSIS)
      cmd.applyTo(program)

    fn = fm.getFunctionAt(entry)
    if fn != null then
      try
        fn.setName(name, SourceType.ANALYSIS)
      catch
        case _: Exception => ()

  private def createUninitializedBlockIfMissing(
    program: Program,
    name: String,
    start: Long,
    end: Long,
    read: Boolean,
    write: Boolean,
    execute: Boolean,
    isVolatile: Boolean = false
  ): Unit =
    val mem = program.getMemory
    val startAddr = addr(program, start)

    if mem.getBlock(startAddr) == null then
      val size = end - start + 1
      val block = mem.createUninitializedBlock(name, startAddr, size, false)
      block.setRead(read)
      block.setWrite(write)
      block.setExecute(execute)
      block.setVolatile(isVolatile)
      Msg.info(this, f"Created block $name @ 0x$start%05X-0x$end%05X")
    else
      Msg.info(this, f"Block already exists for $name @ 0x$start%05X")

  private def setupMemoryMap(program: Program): Unit =
    val tx = program.startTransaction("Setup RL78/G12 memory map")
    try
      // Keep imported ROM if it already exists at 0x00000.
      if program.getMemory.getBlock(addr(program, 0x00000)) == null then
        createUninitializedBlockIfMissing(program, "CODE",       0x00000, 0x007FF, read = true,  write = false, execute = true)

      createUninitializedBlockIfMissing(program, "SFR2",       0xF0000, 0xF07FF, read = true,  write = true,  execute = false, isVolatile = true)
      createUninitializedBlockIfMissing(program, "DATA_FLASH", 0xF1000, 0xF17FF, read = true,  write = true,  execute = false)
      createUninitializedBlockIfMissing(program, "RAM",        0xFFE00, 0xFFEFF, read = true,  write = true,  execute = false)
      createUninitializedBlockIfMissing(program, "SFR",        0xFFF00, 0xFFFFF, read = true,  write = true,  execute = false, isVolatile = true)

      Msg.showInfo(this, null, "RL78G12", "Memory map setup complete.")
    catch
      case e: Exception =>
        Msg.showError(this, null, "RL78G12", s"Failed to setup memory map: ${e.getMessage}", e)
    finally
      program.endTransaction(tx, true)

  private def annotateVectorEntries(program: Program): Unit =
    val mem = program.getMemory

    for ((vec, name) <- vectors) do
      ensureWordData(program, vec.toLong)
      createOrRenameLabel(program, vec.toLong, s"${name}_ADDR")
      setPreComment(program, vec.toLong, s"Interrupt vector entry for $name")

      val vecAddr = addr(program, vec.toLong)
      if mem.contains(vecAddr) && mem.contains(vecAddr.add(1)) then
        val lo = mem.getByte(vecAddr) & 0xff
        val hi = mem.getByte(vecAddr.add(1)) & 0xff
        val target = (hi << 8) | lo

        if target != 0x0000 && target != 0xffff then
          setEolComment(program, vec.toLong, f"Vector target = 0x$target%04X ($name)")
        else
          setEolComment(program, vec.toLong, f"Vector target = 0x$target%04X")

  private def annotateKnownRegions(program: Program): Unit =
    val tx = program.startTransaction("Annotate RL78/G12 regions")
    try
      ensureRegionLabel(program, 0x0000, "VECTOR_TABLE", "Vector table area")
      ensureRegionLabel(program, 0x0080, "CALLT_TABLE", "CALLT table area")
      ensureRegionLabel(program, 0x00C0, "OPTION_BYTES", "Option byte area")
      ensureRegionLabel(program, 0x00C4, "SECURITY_ID", "On-chip debug security ID setting area")

      // Typed bytes/words for well-known ROM regions
      for ((vec, _) <- vectors) do ensureWordData(program, vec.toLong)
      for off <- 0x00C0 to 0x00C3 do ensureByteData(program, off.toLong)
      for off <- 0x00C4 to 0x00CD do ensureByteData(program, off.toLong)

      annotateVectorEntries(program)

      Msg.showInfo(this, null, "RL78G12", "Known regions annotated.")
    catch
      case e: Exception =>
        Msg.showError(this, null, "RL78G12", s"Failed to annotate known regions: ${e.getMessage}", e)
    finally
      program.endTransaction(tx, true)

  private def renameInterrupts(program: Program): Unit =
    val tx = program.startTransaction("Label RL78 interrupt targets")
    try
      val mem = program.getMemory
      val st  = program.getSymbolTable

      for ((vec, name) <- vectors) do
        val vecAddr = addr(program, vec.toLong)

        createOrRenameLabel(program, vec.toLong, s"${name}_ADDR")

        if mem.contains(vecAddr) && mem.contains(vecAddr.add(1)) then
          val lo = mem.getByte(vecAddr) & 0xff
          val hi = mem.getByte(vecAddr.add(1)) & 0xff
          val target = (hi << 8) | lo

          if target != 0x0000 && target != 0xffff then
            val targetAddr = addr(program, target.toLong)

            ensureFunction(program, targetAddr, name)

            val syms = st.getSymbols(targetAddr)
            if syms.isEmpty then
              st.createLabel(targetAddr, name, SourceType.ANALYSIS)
            else
              val primary = st.getPrimarySymbol(targetAddr)
              if primary != null then
                try
                  primary.setName(name, SourceType.ANALYSIS)
                catch
                  case _: Exception =>
                    st.createLabel(targetAddr, f"${name}_${target}%04X", SourceType.ANALYSIS)

            setEolComment(program, vec.toLong, f"target -> $name @ 0x$target%04X")
            setPreComment(program, target.toLong, s"Interrupt handler for $name")

      Msg.showInfo(this, null, "RL78G12", "Interrupt labels added.")
    catch
      case e: Exception =>
        Msg.showError(this, null, "RL78G12", s"Failed to label interrupts: ${e.getMessage}", e)
    finally
      program.endTransaction(tx, true)

  private def renameDecompilerTemps(program: Program): Unit =
    val tx = program.startTransaction("Rename decompiler temps")
    val ifc = new DecompInterface()

    try
      if !ifc.openProgram(program) then
        Msg.showError(this, null, "RL78G12", "Failed to open program in decompiler interface.")
        return

      val fm = program.getFunctionManager
      val it = fm.getFunctions(true)

      var funcsVisited = 0
      var localsRenamed = 0

      while it.hasNext do
        val func = it.next()
        funcsVisited += 1

        val res = ifc.decompileFunction(func, 30, TaskMonitor.DUMMY)

        if res == null then
          Msg.warn(this, s"${func.getName}: decompile returned null")
        else if !res.decompileCompleted() then
          Msg.warn(this, s"${func.getName}: decompile failed: ${res.getErrorMessage}")
        else
          val hf = res.getHighFunction
          if hf == null then
            Msg.warn(this, s"${func.getName}: high function is null")
          else
            HighFunctionDBUtil.commitLocalNamesToDatabase(hf, SourceType.ANALYSIS)

            val locals = func.getLocalVariables
            var localIdx = 1

            for local <- locals do
              val oldName = local.getName
              if isTempName(oldName) then
                val newName = nextUniqueLocalName(func, localIdx)
                localIdx += 1

                try
                  local.setName(newName, SourceType.ANALYSIS)
                  localsRenamed += 1
                catch
                  case _: InvalidInputException =>
                    val fallback = nextUniqueNameFromBase(func, s"${newName}_")
                    try
                      local.setName(fallback, SourceType.ANALYSIS)
                      localsRenamed += 1
                    catch
                      case e: Exception =>
                        Msg.warn(this, s"${func.getName}: failed to rename local $oldName: ${e.getMessage}")
                  case e: Exception =>
                    Msg.warn(this, s"${func.getName}: failed to rename local $oldName: ${e.getMessage}")

        ifc.flushCache()

      Msg.showInfo(
        this,
        null,
        "RL78G12",
        s"Decompiler-temp pass complete. Functions visited: $funcsVisited, locals renamed: $localsRenamed"
      )
    catch
      case e: Exception =>
        Msg.showError(this, null, "RL78G12", s"Failed to rename decompiler temps: ${e.getMessage}", e)
    finally
      ifc.dispose()
      program.endTransaction(tx, true)

  private def isTempName(name: String): Boolean =
    tempVarRe.matches(name)

  private def nextUniqueLocalName(func: Function, startIdx: Int): String =
    var idx = startIdx
    var candidate = s"local_$idx"
    while hasVariableNamed(func, candidate) do
      idx += 1
      candidate = s"local_$idx"
    candidate

  private def nextUniqueNameFromBase(func: Function, base: String): String =
    var idx = 1
    var candidate = s"${base}$idx"
    while hasVariableNamed(func, candidate) do
      idx += 1
      candidate = s"${base}$idx"
    candidate

  private def hasVariableNamed(func: Function, name: String): Boolean =
    func.getAllVariables.exists(_.getName == name)
}
